/* tslint:disable */
/* eslint-disable */
/**
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy\'s Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy\'s Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you\'d like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy\'s <a class=\'wt-text-link wt-p-xs-0\' target=\'_blank\' href=\'https://www.etsy.com/legal/api\'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A representation of structured data values.
 * @export
 * @interface ListingPropertyValue
 */
export interface ListingPropertyValue {
    /**
     * The numeric ID of the Property.
     * @type {number}
     * @memberof ListingPropertyValue
     */
    propertyId?: number;
    /**
     * The name of the Property.
     * @type {string}
     * @memberof ListingPropertyValue
     */
    propertyName?: string | null;
    /**
     * The numeric ID of the scale (if any).
     * @type {number}
     * @memberof ListingPropertyValue
     */
    scaleId?: number | null;
    /**
     * The label used to describe the chosen scale (if any).
     * @type {string}
     * @memberof ListingPropertyValue
     */
    scaleName?: string | null;
    /**
     * The numeric IDs of the Property values
     * @type {Array<number>}
     * @memberof ListingPropertyValue
     */
    valueIds?: Array<number>;
    /**
     * The Property values
     * @type {Array<string>}
     * @memberof ListingPropertyValue
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the ListingPropertyValue interface.
 */
export function instanceOfListingPropertyValue(value: object): value is ListingPropertyValue {
    return true;
}

export function ListingPropertyValueFromJSON(json: any): ListingPropertyValue {
    return ListingPropertyValueFromJSONTyped(json, false);
}

export function ListingPropertyValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingPropertyValue {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyId': json['property_id'] == null ? undefined : json['property_id'],
        'propertyName': json['property_name'] == null ? undefined : json['property_name'],
        'scaleId': json['scale_id'] == null ? undefined : json['scale_id'],
        'scaleName': json['scale_name'] == null ? undefined : json['scale_name'],
        'valueIds': json['value_ids'] == null ? undefined : json['value_ids'],
        'values': json['values'] == null ? undefined : json['values'],
    };
}

export function ListingPropertyValueToJSON(json: any): ListingPropertyValue {
    return ListingPropertyValueToJSONTyped(json, false);
}

export function ListingPropertyValueToJSONTyped(value?: ListingPropertyValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property_id': value['propertyId'],
        'property_name': value['propertyName'],
        'scale_id': value['scaleId'],
        'scale_name': value['scaleName'],
        'value_ids': value['valueIds'],
        'values': value['values'],
    };
}

