/* tslint:disable */
/* eslint-disable */
/**
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy\'s Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy\'s Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you\'d like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy\'s <a class=\'wt-text-link wt-p-xs-0\' target=\'_blank\' href=\'https://www.etsy.com/legal/api\'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents a single user of the site
 * @export
 * @interface Self
 */
export interface Self {
    /**
     * The numeric ID of a user. This number is also a valid shop ID for the user\'s shop.
     * @type {number}
     * @memberof Self
     */
    userId?: number;
    /**
     * The unique positive non-zero numeric ID for an Etsy Shop.
     * @type {number}
     * @memberof Self
     */
    shopId?: number;
}

/**
 * Check if a given object implements the Self interface.
 */
export function instanceOfSelf(value: object): value is Self {
    return true;
}

export function SelfFromJSON(json: any): Self {
    return SelfFromJSONTyped(json, false);
}

export function SelfFromJSONTyped(json: any, ignoreDiscriminator: boolean): Self {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'shopId': json['shop_id'] == null ? undefined : json['shop_id'],
    };
}

export function SelfToJSON(json: any): Self {
    return SelfToJSONTyped(json, false);
}

export function SelfToJSONTyped(value?: Self | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'shop_id': value['shopId'],
    };
}

