/* tslint:disable */
/* eslint-disable */
/**
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy\'s Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy\'s Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you\'d like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy\'s <a class=\'wt-text-link wt-p-xs-0\' target=\'_blank\' href=\'https://www.etsy.com/legal/api\'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A shipping carrier's mail class, which is used to calculate an Estimated Delivery Date.
 * @export
 * @interface ShippingCarrierMailClass
 */
export interface ShippingCarrierMailClass {
    /**
     * The unique identifier of this mail class.
     * @type {string}
     * @memberof ShippingCarrierMailClass
     */
    mailClassKey?: string;
    /**
     * The name of this mail class.
     * @type {string}
     * @memberof ShippingCarrierMailClass
     */
    name?: string;
}

/**
 * Check if a given object implements the ShippingCarrierMailClass interface.
 */
export function instanceOfShippingCarrierMailClass(value: object): value is ShippingCarrierMailClass {
    return true;
}

export function ShippingCarrierMailClassFromJSON(json: any): ShippingCarrierMailClass {
    return ShippingCarrierMailClassFromJSONTyped(json, false);
}

export function ShippingCarrierMailClassFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingCarrierMailClass {
    if (json == null) {
        return json;
    }
    return {
        
        'mailClassKey': json['mail_class_key'] == null ? undefined : json['mail_class_key'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ShippingCarrierMailClassToJSON(json: any): ShippingCarrierMailClass {
    return ShippingCarrierMailClassToJSONTyped(json, false);
}

export function ShippingCarrierMailClassToJSONTyped(value?: ShippingCarrierMailClass | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mail_class_key': value['mailClassKey'],
        'name': value['name'],
    };
}

