/* tslint:disable */
/* eslint-disable */
/**
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy\'s Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy\'s Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you\'d like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy\'s <a class=\'wt-text-link wt-p-xs-0\' target=\'_blank\' href=\'https://www.etsy.com/legal/api\'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A shop created by an Etsy user.
 * @export
 * @interface Shop
 */
export interface Shop {
    /**
     * The unique positive non-zero numeric ID for an Etsy Shop.
     * @type {number}
     * @memberof Shop
     */
    shopId?: number;
    /**
     * The numeric user ID of the [user](/documentation/reference#tag/User) who owns this shop.
     * @type {number}
     * @memberof Shop
     */
    userId?: number;
    /**
     * The shop's name string.
     * @type {string}
     * @memberof Shop
     */
    shopName?: string;
    /**
     * The date and time this shop was created, in epoch seconds.
     * @type {number}
     * @memberof Shop
     */
    createDate?: number;
    /**
     * The date and time this shop was created, in epoch seconds.
     * @type {number}
     * @memberof Shop
     */
    createdTimestamp?: number;
    /**
     * A brief heading string for the shop\'s main page.
     * @type {string}
     * @memberof Shop
     */
    title?: string | null;
    /**
     * An announcement string to buyers that displays on the shop's homepage.
     * @type {string}
     * @memberof Shop
     */
    announcement?: string | null;
    /**
     * The ISO (alphabetic) code for the shop's currency. The shop displays all prices in this currency by default.
     * @type {string}
     * @memberof Shop
     */
    currencyCode?: string;
    /**
     * When true, this shop is not accepting purchases.
     * @type {boolean}
     * @memberof Shop
     */
    isVacation?: boolean;
    /**
     * The shop's message string displayed when `is_vacation` is true.
     * @type {string}
     * @memberof Shop
     */
    vacationMessage?: string | null;
    /**
     * A message string sent to users who complete a purchase from this shop.
     * @type {string}
     * @memberof Shop
     */
    saleMessage?: string | null;
    /**
     * A message string sent to users who purchase a digital item from this shop.
     * @type {string}
     * @memberof Shop
     */
    digitalSaleMessage?: string | null;
    /**
     * The date and time of the last update to the shop, in epoch seconds.
     * @type {number}
     * @memberof Shop
     */
    updateDate?: number;
    /**
     * The date and time of the last update to the shop, in epoch seconds.
     * @type {number}
     * @memberof Shop
     */
    updatedTimestamp?: number;
    /**
     * The number of active listings in the shop.
     * @type {number}
     * @memberof Shop
     */
    listingActiveCount?: number;
    /**
     * The number of digital listings in the shop.
     * @type {number}
     * @memberof Shop
     */
    digitalListingCount?: number;
    /**
     * The shop owner\'s login name string.
     * @type {string}
     * @memberof Shop
     */
    loginName?: string;
    /**
     * When true, the shop accepts customization requests.
     * @type {boolean}
     * @memberof Shop
     */
    acceptsCustomRequests?: boolean;
    /**
     * The shop's policy welcome string (may be blank).
     * @type {string}
     * @memberof Shop
     */
    policyWelcome?: string | null;
    /**
     * The shop's payment policy string (may be blank).
     * @type {string}
     * @memberof Shop
     */
    policyPayment?: string | null;
    /**
     * The shop's shipping policy string (may be blank).
     * @type {string}
     * @memberof Shop
     */
    policyShipping?: string | null;
    /**
     * The shop's refund policy string (may be blank).
     * @type {string}
     * @memberof Shop
     */
    policyRefunds?: string | null;
    /**
     * The shop's additional policies string (may be blank).
     * @type {string}
     * @memberof Shop
     */
    policyAdditional?: string | null;
    /**
     * The shop's seller information string (may be blank).
     * @type {string}
     * @memberof Shop
     */
    policySellerInfo?: string | null;
    /**
     * The date and time of the last update to the shop's policies, in epoch seconds.
     * @type {number}
     * @memberof Shop
     */
    policyUpdateDate?: number;
    /**
     * When true, EU receipts display private info.
     * @type {boolean}
     * @memberof Shop
     */
    policyHasPrivateReceiptInfo?: boolean;
    /**
     * When true, the shop displays additional unstructured policy fields.
     * @type {boolean}
     * @memberof Shop
     */
    hasUnstructuredPolicies?: boolean;
    /**
     * The shop's privacy policy string (may be blank).
     * @type {string}
     * @memberof Shop
     */
    policyPrivacy?: string | null;
    /**
     * The shop's automatic reply string displayed in new conversations when `is_vacation` is true.
     * @type {string}
     * @memberof Shop
     */
    vacationAutoreply?: string | null;
    /**
     * The URL string for this shop.
     * @type {string}
     * @memberof Shop
     */
    url?: string;
    /**
     * The URL string for this shop's banner image.
     * @type {string}
     * @memberof Shop
     */
    imageUrl760x100?: string | null;
    /**
     * The number of users who marked this shop a favorite.
     * @type {number}
     * @memberof Shop
     */
    numFavorers?: number;
    /**
     * A list of language strings for the shop's enrolled languages where the default shop language is the first element in the array.
     * @type {Array<string>}
     * @memberof Shop
     */
    languages?: Array<string>;
    /**
     * The URL string for this shop's icon image.
     * @type {string}
     * @memberof Shop
     */
    iconUrlFullxfull?: string | null;
    /**
     * When true, the shop accepted using structured policies.
     * @type {boolean}
     * @memberof Shop
     */
    isUsingStructuredPolicies?: boolean;
    /**
     * When true, the shop accepted OR declined after viewing structured policies onboarding.
     * @type {boolean}
     * @memberof Shop
     */
    hasOnboardedStructuredPolicies?: boolean;
    /**
     * When true, this shop\'s policies include a link to an EU online dispute form.
     * @type {boolean}
     * @memberof Shop
     */
    includeDisputeFormLink?: boolean;
    /**
     * (**DEPRECATED: Replaced by _is_etsy_payments_onboarded_.) When true, the shop has onboarded onto Etsy Payments.
     * @type {boolean}
     * @memberof Shop
     */
    isDirectCheckoutOnboarded?: boolean;
    /**
     * When true, the shop has onboarded onto Etsy Payments.
     * @type {boolean}
     * @memberof Shop
     */
    isEtsyPaymentsOnboarded?: boolean;
    /**
     * When true, the shop is eligible for calculated shipping profiles. (Only available in the US and Canada)
     * @type {boolean}
     * @memberof Shop
     */
    isCalculatedEligible?: boolean;
    /**
     * When true, the shop opted in to buyer promise.
     * @type {boolean}
     * @memberof Shop
     */
    isOptedInToBuyerPromise?: boolean;
    /**
     * When true, the shop is based in the US.
     * @type {boolean}
     * @memberof Shop
     */
    isShopUsBased?: boolean;
    /**
     * The total number of sales ([transactions](/documentation/reference#tag/Shop-Receipt-Transactions)) for this shop.
     * @type {number}
     * @memberof Shop
     */
    transactionSoldCount?: number;
    /**
     * The country iso the shop is shipping from.
     * @type {string}
     * @memberof Shop
     */
    shippingFromCountryIso?: string | null;
    /**
     * The country iso where the shop is located.
     * @type {string}
     * @memberof Shop
     */
    shopLocationCountryIso?: string | null;
    /**
     * Number of reviews of shop listings in the past year.
     * @type {number}
     * @memberof Shop
     */
    reviewCount?: number | null;
    /**
     * Average rating based on reviews of shop listings in the past year.
     * @type {number}
     * @memberof Shop
     */
    reviewAverage?: number | null;
}

/**
 * Check if a given object implements the Shop interface.
 */
export function instanceOfShop(value: object): value is Shop {
    return true;
}

export function ShopFromJSON(json: any): Shop {
    return ShopFromJSONTyped(json, false);
}

export function ShopFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shop {
    if (json == null) {
        return json;
    }
    return {
        
        'shopId': json['shop_id'] == null ? undefined : json['shop_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'shopName': json['shop_name'] == null ? undefined : json['shop_name'],
        'createDate': json['create_date'] == null ? undefined : json['create_date'],
        'createdTimestamp': json['created_timestamp'] == null ? undefined : json['created_timestamp'],
        'title': json['title'] == null ? undefined : json['title'],
        'announcement': json['announcement'] == null ? undefined : json['announcement'],
        'currencyCode': json['currency_code'] == null ? undefined : json['currency_code'],
        'isVacation': json['is_vacation'] == null ? undefined : json['is_vacation'],
        'vacationMessage': json['vacation_message'] == null ? undefined : json['vacation_message'],
        'saleMessage': json['sale_message'] == null ? undefined : json['sale_message'],
        'digitalSaleMessage': json['digital_sale_message'] == null ? undefined : json['digital_sale_message'],
        'updateDate': json['update_date'] == null ? undefined : json['update_date'],
        'updatedTimestamp': json['updated_timestamp'] == null ? undefined : json['updated_timestamp'],
        'listingActiveCount': json['listing_active_count'] == null ? undefined : json['listing_active_count'],
        'digitalListingCount': json['digital_listing_count'] == null ? undefined : json['digital_listing_count'],
        'loginName': json['login_name'] == null ? undefined : json['login_name'],
        'acceptsCustomRequests': json['accepts_custom_requests'] == null ? undefined : json['accepts_custom_requests'],
        'policyWelcome': json['policy_welcome'] == null ? undefined : json['policy_welcome'],
        'policyPayment': json['policy_payment'] == null ? undefined : json['policy_payment'],
        'policyShipping': json['policy_shipping'] == null ? undefined : json['policy_shipping'],
        'policyRefunds': json['policy_refunds'] == null ? undefined : json['policy_refunds'],
        'policyAdditional': json['policy_additional'] == null ? undefined : json['policy_additional'],
        'policySellerInfo': json['policy_seller_info'] == null ? undefined : json['policy_seller_info'],
        'policyUpdateDate': json['policy_update_date'] == null ? undefined : json['policy_update_date'],
        'policyHasPrivateReceiptInfo': json['policy_has_private_receipt_info'] == null ? undefined : json['policy_has_private_receipt_info'],
        'hasUnstructuredPolicies': json['has_unstructured_policies'] == null ? undefined : json['has_unstructured_policies'],
        'policyPrivacy': json['policy_privacy'] == null ? undefined : json['policy_privacy'],
        'vacationAutoreply': json['vacation_autoreply'] == null ? undefined : json['vacation_autoreply'],
        'url': json['url'] == null ? undefined : json['url'],
        'imageUrl760x100': json['image_url_760x100'] == null ? undefined : json['image_url_760x100'],
        'numFavorers': json['num_favorers'] == null ? undefined : json['num_favorers'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'iconUrlFullxfull': json['icon_url_fullxfull'] == null ? undefined : json['icon_url_fullxfull'],
        'isUsingStructuredPolicies': json['is_using_structured_policies'] == null ? undefined : json['is_using_structured_policies'],
        'hasOnboardedStructuredPolicies': json['has_onboarded_structured_policies'] == null ? undefined : json['has_onboarded_structured_policies'],
        'includeDisputeFormLink': json['include_dispute_form_link'] == null ? undefined : json['include_dispute_form_link'],
        'isDirectCheckoutOnboarded': json['is_direct_checkout_onboarded'] == null ? undefined : json['is_direct_checkout_onboarded'],
        'isEtsyPaymentsOnboarded': json['is_etsy_payments_onboarded'] == null ? undefined : json['is_etsy_payments_onboarded'],
        'isCalculatedEligible': json['is_calculated_eligible'] == null ? undefined : json['is_calculated_eligible'],
        'isOptedInToBuyerPromise': json['is_opted_in_to_buyer_promise'] == null ? undefined : json['is_opted_in_to_buyer_promise'],
        'isShopUsBased': json['is_shop_us_based'] == null ? undefined : json['is_shop_us_based'],
        'transactionSoldCount': json['transaction_sold_count'] == null ? undefined : json['transaction_sold_count'],
        'shippingFromCountryIso': json['shipping_from_country_iso'] == null ? undefined : json['shipping_from_country_iso'],
        'shopLocationCountryIso': json['shop_location_country_iso'] == null ? undefined : json['shop_location_country_iso'],
        'reviewCount': json['review_count'] == null ? undefined : json['review_count'],
        'reviewAverage': json['review_average'] == null ? undefined : json['review_average'],
    };
}

export function ShopToJSON(json: any): Shop {
    return ShopToJSONTyped(json, false);
}

export function ShopToJSONTyped(value?: Shop | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shop_id': value['shopId'],
        'user_id': value['userId'],
        'shop_name': value['shopName'],
        'create_date': value['createDate'],
        'created_timestamp': value['createdTimestamp'],
        'title': value['title'],
        'announcement': value['announcement'],
        'currency_code': value['currencyCode'],
        'is_vacation': value['isVacation'],
        'vacation_message': value['vacationMessage'],
        'sale_message': value['saleMessage'],
        'digital_sale_message': value['digitalSaleMessage'],
        'update_date': value['updateDate'],
        'updated_timestamp': value['updatedTimestamp'],
        'listing_active_count': value['listingActiveCount'],
        'digital_listing_count': value['digitalListingCount'],
        'login_name': value['loginName'],
        'accepts_custom_requests': value['acceptsCustomRequests'],
        'policy_welcome': value['policyWelcome'],
        'policy_payment': value['policyPayment'],
        'policy_shipping': value['policyShipping'],
        'policy_refunds': value['policyRefunds'],
        'policy_additional': value['policyAdditional'],
        'policy_seller_info': value['policySellerInfo'],
        'policy_update_date': value['policyUpdateDate'],
        'policy_has_private_receipt_info': value['policyHasPrivateReceiptInfo'],
        'has_unstructured_policies': value['hasUnstructuredPolicies'],
        'policy_privacy': value['policyPrivacy'],
        'vacation_autoreply': value['vacationAutoreply'],
        'url': value['url'],
        'image_url_760x100': value['imageUrl760x100'],
        'num_favorers': value['numFavorers'],
        'languages': value['languages'],
        'icon_url_fullxfull': value['iconUrlFullxfull'],
        'is_using_structured_policies': value['isUsingStructuredPolicies'],
        'has_onboarded_structured_policies': value['hasOnboardedStructuredPolicies'],
        'include_dispute_form_link': value['includeDisputeFormLink'],
        'is_direct_checkout_onboarded': value['isDirectCheckoutOnboarded'],
        'is_etsy_payments_onboarded': value['isEtsyPaymentsOnboarded'],
        'is_calculated_eligible': value['isCalculatedEligible'],
        'is_opted_in_to_buyer_promise': value['isOptedInToBuyerPromise'],
        'is_shop_us_based': value['isShopUsBased'],
        'transaction_sold_count': value['transactionSoldCount'],
        'shipping_from_country_iso': value['shippingFromCountryIso'],
        'shop_location_country_iso': value['shopLocationCountryIso'],
        'review_count': value['reviewCount'],
        'review_average': value['reviewAverage'],
    };
}

