/* tslint:disable */
/* eslint-disable */
/**
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy\'s Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy\'s Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you\'d like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy\'s <a class=\'wt-text-link wt-p-xs-0\' target=\'_blank\' href=\'https://www.etsy.com/legal/api\'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The record of one shipment event for a ShopReceipt. A receipt may have many ShopReceiptShipment records.
 * @export
 * @interface ShopReceiptShipment
 */
export interface ShopReceiptShipment {
    /**
     * The unique numeric ID of a Shop Receipt Shipment record.
     * @type {number}
     * @memberof ShopReceiptShipment
     */
    receiptShippingId?: number | null;
    /**
     * The time at which Etsy notified the buyer of the shipment event, in epoch seconds.
     * @type {number}
     * @memberof ShopReceiptShipment
     */
    shipmentNotificationTimestamp?: number;
    /**
     * The name string for the carrier/company responsible for delivering the shipment.
     * @type {string}
     * @memberof ShopReceiptShipment
     */
    carrierName?: string;
    /**
     * The tracking code string provided by the carrier/company for the shipment.
     * @type {string}
     * @memberof ShopReceiptShipment
     */
    trackingCode?: string;
}

/**
 * Check if a given object implements the ShopReceiptShipment interface.
 */
export function instanceOfShopReceiptShipment(value: object): value is ShopReceiptShipment {
    return true;
}

export function ShopReceiptShipmentFromJSON(json: any): ShopReceiptShipment {
    return ShopReceiptShipmentFromJSONTyped(json, false);
}

export function ShopReceiptShipmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopReceiptShipment {
    if (json == null) {
        return json;
    }
    return {
        
        'receiptShippingId': json['receipt_shipping_id'] == null ? undefined : json['receipt_shipping_id'],
        'shipmentNotificationTimestamp': json['shipment_notification_timestamp'] == null ? undefined : json['shipment_notification_timestamp'],
        'carrierName': json['carrier_name'] == null ? undefined : json['carrier_name'],
        'trackingCode': json['tracking_code'] == null ? undefined : json['tracking_code'],
    };
}

export function ShopReceiptShipmentToJSON(json: any): ShopReceiptShipment {
    return ShopReceiptShipmentToJSONTyped(json, false);
}

export function ShopReceiptShipmentToJSONTyped(value?: ShopReceiptShipment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'receipt_shipping_id': value['receiptShippingId'],
        'shipment_notification_timestamp': value['shipmentNotificationTimestamp'],
        'carrier_name': value['carrierName'],
        'tracking_code': value['trackingCode'],
    };
}

