/* tslint:disable */
/* eslint-disable */
/**
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy\'s Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy\'s Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you\'d like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy\'s <a class=\'wt-text-link wt-p-xs-0\' target=\'_blank\' href=\'https://www.etsy.com/legal/api\'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A file associated with a digital listing.
 * @export
 * @interface ShopListingFile
 */
export interface ShopListingFile {
    /**
     * The unique numeric ID of a file associated with a digital listing.
     * @type {number}
     * @memberof ShopListingFile
     */
    listingFileId?: number;
    /**
     * The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
     * @type {number}
     * @memberof ShopListingFile
     */
    listingId?: number;
    /**
     * The numeric index of the display order position of this file in the listing, starting at 1.
     * @type {number}
     * @memberof ShopListingFile
     */
    rank?: number;
    /**
     * The file name string for a file associated with a digital listing.
     * @type {string}
     * @memberof ShopListingFile
     */
    filename?: string;
    /**
     * A human-readable format size string for the size of a file.
     * @type {string}
     * @memberof ShopListingFile
     */
    filesize?: string;
    /**
     * A number indicating the size of a file, measured in bytes.
     * @type {number}
     * @memberof ShopListingFile
     */
    sizeBytes?: number;
    /**
     * A type string indicating a file's MIME type.
     * @type {string}
     * @memberof ShopListingFile
     */
    filetype?: string;
    /**
     * The unique numeric ID of a file associated with a digital listing.
     * @type {number}
     * @memberof ShopListingFile
     */
    createTimestamp?: number;
    /**
     * The unique numeric ID of a file associated with a digital listing.
     * @type {number}
     * @memberof ShopListingFile
     */
    createdTimestamp?: number;
}

/**
 * Check if a given object implements the ShopListingFile interface.
 */
export function instanceOfShopListingFile(value: object): value is ShopListingFile {
    return true;
}

export function ShopListingFileFromJSON(json: any): ShopListingFile {
    return ShopListingFileFromJSONTyped(json, false);
}

export function ShopListingFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopListingFile {
    if (json == null) {
        return json;
    }
    return {
        
        'listingFileId': json['listing_file_id'] == null ? undefined : json['listing_file_id'],
        'listingId': json['listing_id'] == null ? undefined : json['listing_id'],
        'rank': json['rank'] == null ? undefined : json['rank'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'filesize': json['filesize'] == null ? undefined : json['filesize'],
        'sizeBytes': json['size_bytes'] == null ? undefined : json['size_bytes'],
        'filetype': json['filetype'] == null ? undefined : json['filetype'],
        'createTimestamp': json['create_timestamp'] == null ? undefined : json['create_timestamp'],
        'createdTimestamp': json['created_timestamp'] == null ? undefined : json['created_timestamp'],
    };
}

export function ShopListingFileToJSON(json: any): ShopListingFile {
    return ShopListingFileToJSONTyped(json, false);
}

export function ShopListingFileToJSONTyped(value?: ShopListingFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listing_file_id': value['listingFileId'],
        'listing_id': value['listingId'],
        'rank': value['rank'],
        'filename': value['filename'],
        'filesize': value['filesize'],
        'size_bytes': value['sizeBytes'],
        'filetype': value['filetype'],
        'create_timestamp': value['createTimestamp'],
        'created_timestamp': value['createdTimestamp'],
    };
}

