/* tslint:disable */
/* eslint-disable */
/**
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy\'s Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy\'s Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you\'d like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy\'s <a class=\'wt-text-link wt-p-xs-0\' target=\'_blank\' href=\'https://www.etsy.com/legal/api\'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';

/**
 * Represents a shipping destination assigned to a shipping profile.
 * @export
 * @interface ShopShippingProfileDestination
 */
export interface ShopShippingProfileDestination {
    /**
     * The numeric ID of the shipping profile destination in the [shipping profile](/documentation/reference#tag/Shop-ShippingProfile) associated with the listing.
     * @type {number}
     * @memberof ShopShippingProfileDestination
     */
    shippingProfileDestinationId?: number;
    /**
     * The numeric ID of the shipping profile.
     * @type {number}
     * @memberof ShopShippingProfileDestination
     */
    shippingProfileId?: number;
    /**
     * The ISO code of the country from which the listing ships.
     * @type {string}
     * @memberof ShopShippingProfileDestination
     */
    originCountryIso?: string;
    /**
     * The ISO code of the country to which the listing ships. If null, request sets destination to destination_region. Required if destination_region is null or not provided.
     * @type {string}
     * @memberof ShopShippingProfileDestination
     */
    destinationCountryIso?: string;
    /**
     * The code of the region to which the listing ships. A region represents a set of countries. Supported regions are Europe Union and Non-Europe Union (countries in Europe not in EU). If \`none\`, request sets destination to destination_country_iso. Required if destination_country_iso is null or not provided.
     * @type {string}
     * @memberof ShopShippingProfileDestination
     */
    destinationRegion?: ShopShippingProfileDestinationDestinationRegionEnum;
    /**
     * The cost of shipping to this country/region alone, measured in the store's default currency.
     * @type {Money}
     * @memberof ShopShippingProfileDestination
     */
    primaryCost?: Money;
    /**
     * The cost of shipping to this country/region with another item, measured in the store's default currency.
     * @type {Money}
     * @memberof ShopShippingProfileDestination
     */
    secondaryCost?: Money;
    /**
     * The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.
     * @type {number}
     * @memberof ShopShippingProfileDestination
     */
    shippingCarrierId?: number | null;
    /**
     * The unique ID string of a shipping carrier's mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.
     * @type {string}
     * @memberof ShopShippingProfileDestination
     */
    mailClass?: string | null;
    /**
     * The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.
     * @type {number}
     * @memberof ShopShippingProfileDestination
     */
    minDeliveryDays?: number | null;
    /**
     * The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.
     * @type {number}
     * @memberof ShopShippingProfileDestination
     */
    maxDeliveryDays?: number | null;
}


/**
 * @export
 */
export const ShopShippingProfileDestinationDestinationRegionEnum = {
    Eu: 'eu',
    NonEu: 'non_eu',
    None: 'none'
} as const;
export type ShopShippingProfileDestinationDestinationRegionEnum = typeof ShopShippingProfileDestinationDestinationRegionEnum[keyof typeof ShopShippingProfileDestinationDestinationRegionEnum];


/**
 * Check if a given object implements the ShopShippingProfileDestination interface.
 */
export function instanceOfShopShippingProfileDestination(value: object): value is ShopShippingProfileDestination {
    return true;
}

export function ShopShippingProfileDestinationFromJSON(json: any): ShopShippingProfileDestination {
    return ShopShippingProfileDestinationFromJSONTyped(json, false);
}

export function ShopShippingProfileDestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopShippingProfileDestination {
    if (json == null) {
        return json;
    }
    return {
        
        'shippingProfileDestinationId': json['shipping_profile_destination_id'] == null ? undefined : json['shipping_profile_destination_id'],
        'shippingProfileId': json['shipping_profile_id'] == null ? undefined : json['shipping_profile_id'],
        'originCountryIso': json['origin_country_iso'] == null ? undefined : json['origin_country_iso'],
        'destinationCountryIso': json['destination_country_iso'] == null ? undefined : json['destination_country_iso'],
        'destinationRegion': json['destination_region'] == null ? undefined : json['destination_region'],
        'primaryCost': json['primary_cost'] == null ? undefined : MoneyFromJSON(json['primary_cost']),
        'secondaryCost': json['secondary_cost'] == null ? undefined : MoneyFromJSON(json['secondary_cost']),
        'shippingCarrierId': json['shipping_carrier_id'] == null ? undefined : json['shipping_carrier_id'],
        'mailClass': json['mail_class'] == null ? undefined : json['mail_class'],
        'minDeliveryDays': json['min_delivery_days'] == null ? undefined : json['min_delivery_days'],
        'maxDeliveryDays': json['max_delivery_days'] == null ? undefined : json['max_delivery_days'],
    };
}

export function ShopShippingProfileDestinationToJSON(json: any): ShopShippingProfileDestination {
    return ShopShippingProfileDestinationToJSONTyped(json, false);
}

export function ShopShippingProfileDestinationToJSONTyped(value?: ShopShippingProfileDestination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shipping_profile_destination_id': value['shippingProfileDestinationId'],
        'shipping_profile_id': value['shippingProfileId'],
        'origin_country_iso': value['originCountryIso'],
        'destination_country_iso': value['destinationCountryIso'],
        'destination_region': value['destinationRegion'],
        'primary_cost': MoneyToJSON(value['primaryCost']),
        'secondary_cost': MoneyToJSON(value['secondaryCost']),
        'shipping_carrier_id': value['shippingCarrierId'],
        'mail_class': value['mailClass'],
        'min_delivery_days': value['minDeliveryDays'],
        'max_delivery_days': value['maxDeliveryDays'],
    };
}

