/* tslint:disable */
/* eslint-disable */
/**
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy\'s Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy\'s Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you\'d like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy\'s <a class=\'wt-text-link wt-p-xs-0\' target=\'_blank\' href=\'https://www.etsy.com/legal/api\'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A list of variations chosen by the buyer during checkout.
 * @export
 * @interface TransactionVariations
 */
export interface TransactionVariations {
    /**
     * The variation property ID.
     * @type {number}
     * @memberof TransactionVariations
     */
    propertyId?: number;
    /**
     * The ID of the variation value selected.
     * @type {number}
     * @memberof TransactionVariations
     */
    valueId?: number | null;
    /**
     * Formatted name of the variation.
     * @type {string}
     * @memberof TransactionVariations
     */
    formattedName?: string;
    /**
     * Value of the variation entered by the buyer.
     * @type {string}
     * @memberof TransactionVariations
     */
    formattedValue?: string;
}

/**
 * Check if a given object implements the TransactionVariations interface.
 */
export function instanceOfTransactionVariations(value: object): value is TransactionVariations {
    return true;
}

export function TransactionVariationsFromJSON(json: any): TransactionVariations {
    return TransactionVariationsFromJSONTyped(json, false);
}

export function TransactionVariationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionVariations {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyId': json['property_id'] == null ? undefined : json['property_id'],
        'valueId': json['value_id'] == null ? undefined : json['value_id'],
        'formattedName': json['formatted_name'] == null ? undefined : json['formatted_name'],
        'formattedValue': json['formatted_value'] == null ? undefined : json['formatted_value'],
    };
}

export function TransactionVariationsToJSON(json: any): TransactionVariations {
    return TransactionVariationsToJSONTyped(json, false);
}

export function TransactionVariationsToJSONTyped(value?: TransactionVariations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property_id': value['propertyId'],
        'value_id': value['valueId'],
        'formatted_name': value['formattedName'],
        'formatted_value': value['formattedValue'],
    };
}

